feat(traefik): Add error handling to entrypoint script

diff --git a/rendered/envs/alpha/traefik/daemonset-traefik.yaml b/rendered/envs/alpha/traefik/daemonset-traefik.yaml
--- a/rendered/envs/alpha/traefik/daemonset-traefik.yaml
+++ b/rendered/envs/alpha/traefik/daemonset-traefik.yaml
@@ -72,6 +72,23 @@ spec:
 
               set -euo pipefail
 
+              function script_error_trap() {
+                local last_exit_code=$?
+                local line_number=$LINENO
+
+                echo "--- Script Failed Unexpectedly ---" >&2
+                echo "Error on line $line_number" >&2
+                echo "Exit code: $last_exit_code" >&2
+                echo "Failing command: $BASH_COMMAND" >&2
+                echo "-----------------------------------" >&2
+
+                echo "Last known NODE_IPV6: $NODE_IPV6" >&2
+
+                exit $last_exit_code
+              }
+
+              trap script_error_trap ERR
+
               function get_ipv6() {
                 nslookup -type=aaaa "${HOSTNAME:?}.${BASE_DOMAIN:?}" 1.1.1.1 \
                   | grep '^Address:' \
